### ISSUE TITLE
Add cache support

### ISSUE THREAD

**Issue by phated** [phated/github-download-directory#3]
I just noticed https://github.com/devsu/github-download-directory/commit/d5022020803e5eec4bd95bf9572c6f6badbd883e where @c3s4r added cache support for the library. I think having this feature makes a ton of sense; however I don't want to tie people into filesystem access.

I think we can use https://www.npmjs.com/package/keyv and a `new Map()` for the built-in cache but then people can use different adapters if they want different backends.

**Comment by c3s4r** [comment]
Hi. I'm storing the cache on the disk on purpose. I'm using this package in a CLI tool, and thus, I cannot have it just in memory, because I need it to persist on multiple executions.

Anyways, for sure the implementation can be improved, in order to have optional disk persistence.

**Comment by phated** [comment]
Just published 2.0.0 with cache support. It required a new API, so check out the README usage examples or tests for that.
