### ISSUE TITLE
Feat req: Ability to download from private repos

### ISSUE THREAD

**Issue by corysimmons** [phated/github-download-directory#5]
Please?

**Comment by phated** [comment]
@corysimmons does https://github.com/phated/github-download-directory/commit/f53a426f4e71b733f04754f47dd4313768b4dc23 work?

**Comment by phated** [comment]
Just published 2.0.0 which switched to using octokit. It required a changing API, so check out the README usage examples or tests for that.

You can pass any octokit client configuration as `{ github: {} }` to the Downloader constructor.

**Comment by corysimmons** [comment]
Very cool thank you.
